# Numpy Excercises

### Creation of one dimensional numpy array

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4 ,5])
print("Array 1: ", arr1)

arr2 = np.arange(1, 10, 2)
print("Array 2: ", arr2)

arr3 = np.linspace(1, 50, 5)
print("Array 3: ", arr3)

arr4 = np.random.rand(5)
print("Array 4: ", arr4)

arr5 = np.random.randint(1, 10, 3)
print("Array 5: ", arr5)

arr6 = np.zeros(5)
print("Array 6: ", arr6)

arr7 = np.ones(8)
print("Array 7: ", arr7)

arr8 = np.full(8, 9)
print("Array 8: ", arr8)

Array 1:  [1 2 3 4 5]
Array 2:  [1 3 5 7 9]
Array 3:  [ 1.   13.25 25.5  37.75 50.  ]
Array 4:  [0.81556184 0.19265124 0.45029463 0.45093021 0.11162935]
Array 5:  [9 5 6]
Array 6:  [0. 0. 0. 0. 0.]
Array 7:  [1. 1. 1. 1. 1. 1. 1. 1.]
Array 8:  [9 9 9 9 9 9 9 9]


### Creating multi dimensional arrays

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
print("Two dimensional array: \n", arr1)

arr2 = np.arange(0, 9)
print("Using reshape: \n", arr2.reshape(3, 3))

arr3 = np.ones((2,2))
print("Ones: \n", arr3)

arr4 = np.random.randint(1, 100, size=(3, 3))
print("randint: \n", arr4)

arr5 = np.full((2, 2), 5)
print(arr5)

arr6 = np.random.randint(1, 100, size=(3, 3, 3))
print(arr6)

Two dimensional array: 
 [[1 2]
 [3 4]]
Using reshape: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Ones: 
 [[1. 1.]
 [1. 1.]]
randint: 
 [[91  4 11]
 [60 14 59]
 [81 39 55]]
[[5 5]
 [5 5]]
[[[33 75 66]
  [97 78 71]
  [12 24 40]]

 [[52 13 59]
  [99  5 58]
  [51 23 48]]

 [[ 6 77 19]
  [12 73 10]
  [19 44 93]]]


### Properties of arrays

In [4]:
arr1 = np.arange(1, 10).reshape(3, 3)

print("Dimensions: ", arr1.ndim)
print("Shape: ", arr1.shape)
print("size: ", arr1.size)
print("Data type: ", arr1.dtype)

arr1 = arr1.astype(np.float32)
print("Data type: ", arr1.dtype)



Dimensions:  2
Shape:  (3, 3)
size:  9
Data type:  int64
Data type:  float32


### Indexing and slicing

In [5]:
arr1 = np.arange(10)
arr2 = np.arange(1, 17).reshape(4, 4)

print(arr1[5])
print(arr1[3:7])
print(arr1[::2])
print(arr1[::-1])

print(arr2[1])
print(arr2[:,3])
print(arr2[2,1])
print(arr2[:2,2:])
print(arr2[1:3,1:3])
print(arr2[::3,::3])


5
[3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[5 6 7 8]
[ 4  8 12 16]
10
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]
[[ 1  4]
 [13 16]]


### Boolean Masking

In [6]:
arr1 = np.array([-5, 2, 8, -1, 0, 7, -3, 10, 4, -8])

arr2 = np.random.randint(1, 100, size=(4, 4))

print("Less than 0: ", arr1[arr1 < 0])
print("Even numbers: ", arr1[arr1 % 2 == 0])
print("Greater than 0 and less than 6: ", arr1[(arr1 > 0) & (arr1 < 6)])
print("Exactly 0 or 10: ", arr1[(arr1 == 0) | (arr1 == 10)])


print("Greater than 80: ", arr2[arr2 > 80])
print("Replacing every number less than 30 with 0")
arr3 = arr2.copy()
arr3[arr3 < 30] = 0

print(arr3)

print("count of numbers greater than 50: ", (arr2 > 50).sum())

arr3 = np.arange(27).reshape(3, 3, 3)

print("number greater than 15: ", arr3[arr3 > 15])


Less than 0:  [-5 -1 -3 -8]
Even numbers:  [ 2  8  0 10  4 -8]
Greater than 0 and less than 6:  [2 4]
Exactly 0 or 10:  [ 0 10]
Greater than 80:  [93 96 87]
Replacing every number less than 30 with 0
[[ 0  0 39  0]
 [93 69 57 52]
 [37  0 30  0]
 [64 96 87 51]]
count of numbers greater than 50:  8
number greater than 15:  [16 17 18 19 20 21 22 23 24 25 26]


### Axis on aggreagating functions

In [ ]:
arr1 = np.random.rand(5, 24)
# print(arr1)

print("Maximum of each row: ", arr1.max(axis=1))
print("Shape: ", arr1.max(axis=1).shape)

print("Average of each column: ", arr1.mean(axis = 0))

Maximum of each row:  [0.97646808 0.98192465 0.99249727 0.88766691 0.90485585]
Shape:  (5,)
Average of each column:  [0.48661742 0.57739863 0.41318161 0.46045623 0.71819605 0.46322076
 0.56693994 0.45893721 0.4014569  0.572349   0.57692821 0.68133062
 0.25783326 0.75041009 0.33127088 0.55623154 0.59603811 0.61364261
 0.41716872 0.46079723 0.36685193 0.72975023 0.36993326 0.47202265]


In [14]:
arr = np.random.randint(2000, 15000, size=(12, 4 , 7))

print(arr.sum(axis = 2))
print(arr.sum(axis = 2).shape)
print(arr.mean(axis = 0).mean(axis = 0))
print(arr.mean(axis = 0).mean(axis = 0).shape)

[[65423 60602 56287 65682]
 [67404 46979 76214 62298]
 [70916 74290 61147 76104]
 [49752 70719 65707 64924]
 [56558 61336 63495 62546]
 [69112 66889 61555 65653]
 [64145 64257 63672 64111]
 [71079 44511 61196 50291]
 [67660 56908 67910 64798]
 [60495 57666 56597 67707]
 [61463 56908 51719 64040]
 [51378 58147 75874 65167]]
(12, 4)
[8889.75       9602.02083333 8391.         8293.22916667 8914.91666667
 9022.45833333 9580.1875    ]
(7,)


### Concatenation and clipping

In [22]:
arr1 = np.arange(9).reshape(3, 3)
arr2 = np.arange(9, 18).reshape(3, 3)

# print(np.concatenate(arr1, arr2))
print(np.concatenate((arr1, arr2), axis = 0))
print()
print(np.concatenate((arr1, arr2), axis = 1))


arr3 = np.arange(1, 20)
arr3 = np.clip(arr3 + 20, 10, 25)
print(arr3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]
[21 22 23 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25]


### Broadcasting

In [27]:
arr1 = np.linspace(1, 100, 25)
arr2 = np.linspace(1, 100, 25)

print(arr1 + arr2)
print()
print(arr1 ** arr2)
print()
print(np.sqrt(arr1))
print()
print(np.sin(arr1))


[  2.    10.25  18.5   26.75  35.    43.25  51.5   59.75  68.    76.25
  84.5   92.75 101.   109.25 117.5  125.75 134.   142.25 150.5  158.75
 167.   175.25 183.5  191.75 200.  ]

[1.00000000e+000 4.33691672e+003 8.64591632e+008 1.15925626e+015
 5.66455571e+021 7.38628416e+028 2.12575769e+036 1.18802049e+044
 1.17566389e+052 1.92143466e+060 4.91109841e+068 1.87895730e+077
 1.03804121e+086 8.03540841e+094 8.49595920e+103 1.20033958e+113
 2.22337020e+122 5.30987897e+131 1.61107013e+141 6.12910029e+150
 2.88948672e+160 1.67024898e+170 1.17248472e+180 9.90838825e+189
 1.00000000e+200]

[ 1.          2.26384628  3.04138127  3.65718471  4.18330013  4.65026881
  5.07444578  5.46580278  5.83095189  6.17454452  6.5         6.80991924
  7.1063352   7.39087275  7.66485486  7.92937576  8.18535277  8.4335639
  8.67467579  8.90926484  9.13783344  9.36082261  9.57862203  9.79157801
 10.        ]

[ 0.84147098 -0.91607692  0.17388949  0.72334146 -0.97562601  0.35802197
  0.57880195 -0.99955393  0.5290

In [41]:
arr = np.random.randint(1, 100, size=(3, 3))
print(arr)
arr.sort(axis=0)
print(arr)


arr1 = np.arange(10, 1, -1)
print(arr1)
arr1.sort()
print(arr1)


[[39 45 98]
 [72 95 13]
 [33 38 67]]
[[33 38 13]
 [39 45 67]
 [72 95 98]]
[10  9  8  7  6  5  4  3  2]
[ 2  3  4  5  6  7  8  9 10]
